In [62]:
import numpy as np 
import pandas as pd

In [63]:
df = pd.read_csv("ml_traindata.csv")
df.head(5)

,id,title,categories
0,1,TUNGSTEN SOLDER PICK WITH HANDLE,"Arts, Crafts & Sewing"
1,2,Write Right 98167 Screen Protector for Sony T615C,Cell Phones & Accessories
2,3,Casio Mens DBC310-1 Databank 300 Digital Watch...,"Clothing, Shoes & Jewelry"
3,4,Factory-Reconditioned DEWALT DW260KR Heavy-Dut...,Tools & Home Improvement
4,5,Energizer 2 in 1 Light,Health & Personal Care

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46229 entries, 0 to 46228
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          46229 non-null  int64
 1   title       46228 non-null  object
 2   categories  46229 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.1+ MB

In [65]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
46224    False
46225    False
46226    False
46227    False
46228    False
Length: 46229, dtype: bool

In [66]:
df['categories'].unique()

array(['Arts, Crafts & Sewing', 'Cell Phones & Accessories',
       'Clothing, Shoes & Jewelry', 'Tools & Home Improvement',
       'Health & Personal Care', 'Baby Products', 'Baby',
       'Patio, Lawn & Garden', 'Beauty', 'Sports & Outdoors',
       'Electronics', 'All Electronics', 'Automotive', 'Toys & Games',
       'All Beauty', 'Office Products', 'Appliances',
       'Musical Instruments', 'Industrial & Scientific',
       'Grocery & Gourmet Food', 'Pet Supplies'], dtype=object)

In [67]:
category_map = {
    'Arts, Crafts & Sewing': 'Lifestyle & Fashion',
    'Clothing, Shoes & Jewelry': 'Lifestyle & Fashion',

    'Beauty': 'Health & Personal Care',
    'All Beauty': 'Health & Personal Care',
    'Health & Personal Care': 'Health & Personal Care',

    'Electronics': 'Electronics & Tech',
    'All Electronics': 'Electronics & Tech',
    'Cell Phones & Accessories': 'Electronics & Tech',
    'Office Products': 'Electronics & Tech',
    
    'Tools & Home Improvement': 'Home & Tools',
    'Patio, Lawn & Garden': 'Home & Tools',
    'Appliances': 'Home & Tools',
    'Industrial & Scientific': 'Home & Tools',
    
    'Baby Products': 'Baby Products',
    'Baby': 'Baby Products',
    
    'Sports & Outdoors': 'Leisure & Hobbies',
    'Toys & Games': 'Leisure & Hobbies',
    'Musical Instruments': 'Leisure & Hobbies'
}
df['categories'] = df['categories'].replace(category_map)

In [73]:
df['categories'].nunique()

9

In [69]:
df = df.replace(r'["()]', '', regex=True)
df = df.replace('-', ' ', regex=True)
df = df.replace('/', '', regex=True)
df = df.replace('  ', ' ', regex=True)
df['title'] = df['title'].str.replace(r'["\d]', '', regex=True)
df.head(5)

,id,title,categories
0,1,TUNGSTEN SOLDER PICK WITH HANDLE,Lifestyle & Fashion
1,2,Write Right Screen Protector for Sony TC,Electronics & Tech
2,3,Casio Mens DBC Databank Digital Watch Discon...,Lifestyle & Fashion
3,4,Factory Reconditioned DEWALT DWKR Heavy Duty ....,Home & Tools
4,5,Energizer in Light,Health & Personal Care

In [70]:
df['title'] = df['title'].str.replace('&amp;', '&')
df['title'] = df['title'].str.replace('&quot;', '')
df['title'] = df['title'].str.replace(r'[^\w\s]', '', regex=True)
df['title'] = df['title'].replace('', pd.NA)
df = df.dropna(subset=['title', 'categories'])
df['title'] = df['title'].str.replace(r'([a-z])([A-Z])', r'\1 \2', regex=True)
df['title'] = df['title'].str.replace(r'\s+', ' ', regex=True)
df['title'] = df['title'].str.strip()

In [71]:
df['title'] = df['title'].str.lower()
df['categories'] = df['categories'].str.lower()

In [72]:
df.to_csv('clean_data.csv', index = False)